Added a papers directory for papers.  These are done in OpenOffice and converted to pdf by converting the OpenOffice file to Latex using writer2latex.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all gc libltdl"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP EGREP CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT RFLAG EFENCE GCC_VERSION GCC_MAJOR GCC_MINOR PERLPROG CXXPROG host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL INSTALL_LTDL_TRUE INSTALL_LTDL_FALSE CONVENIENCE_LTDL_TRUE CONVENIENCE_LTDL_FALSE LIBADD_DL LIBLTDL INCLTDL SKRIBE PDFLATEX LATEXOK_TRUE LATEXOK_FALSE PROFILE ACLOCAL_FLAGS WEBHOME DOCDIR CompileOk_TRUE CompileOk_FALSE COMPILE_OK CONFOPTS subdirs LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP EGREP CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT RFLAG EFENCE GCC_VERSION GCC_MAJOR GCC_MINOR PERLPROG CXXPROG host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL INSTALL_LTDL_TRUE INSTALL_LTDL_FALSE CONVENIENCE_LTDL_TRUE CONVENIENCE_LTDL_FALSE LIBADD_DL LIBLTDL INCLTDL SKRIBE BIBTEX PDFLATEX TRIP W2L LATEXOK_TRUE LATEXOK_FALSE SKRIBEOK_TRUE SKRIBEOK_FALSE RSTOK_TRUE RSTOK_FALSE W2LOK_TRUE W2LOK_FALSE PROFILE ACLOCAL_FLAGS WEBHOME DOCDIR CompileOk_TRUE CompileOk_FALSE COMPILE_OK CONFOPTS subdirs LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -22772,7 +22772,7 @@ echo "$as_me: error: Failed to configure Quickthreads." >&2;}
 
 
 
-## Configure Skribe and Latex.
+## Configure the documentation tools.
 
 
 # Extract the first word of "skribe", so it can be a program name with args.
@@ -22814,11 +22814,43 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-if test "x$SKRIBE" = x ; then
-  echo "The skribe program was not found.  Documentation will not be built."
-  echo "To build the documentation, make sure that skribe is installed and in your path."
-  echo "You can find skribe here:  http://www-sop.inria.fr/mimosa/fp/Skribe/"
-  DOCDIR=
+# Extract the first word of "bibtex", so it can be a program name with args.
+set dummy bibtex; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_BIBTEX+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $BIBTEX in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_BIBTEX="$BIBTEX" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_BIBTEX="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+BIBTEX=$ac_cv_path_BIBTEX
+
+if test -n "$BIBTEX"; then
+  echo "$as_me:$LINENO: result: $BIBTEX" >&5
+echo "${ECHO_T}$BIBTEX" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "pdflatex", so it can be a program name with args.
@@ -22860,10 +22892,86 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-
-if [ x$PDFLATEX = x ] ; then
-  echo "PDF documentation will not be build because pdflatex could not be found."
+# Extract the first word of "trip", so it can be a program name with args.
+set dummy trip; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_TRIP+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
 else
+  case $TRIP in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_TRIP="$TRIP" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_TRIP="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+TRIP=$ac_cv_path_TRIP
+
+if test -n "$TRIP"; then
+  echo "$as_me:$LINENO: result: $TRIP" >&5
+echo "${ECHO_T}$TRIP" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+# Extract the first word of "w2l", so it can be a program name with args.
+set dummy w2l; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_W2L+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $W2L in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_W2L="$W2L" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_W2L="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+W2L=$ac_cv_path_W2L
+
+if test -n "$W2L"; then
+  echo "$as_me:$LINENO: result: $W2L" >&5
+echo "${ECHO_T}$W2L" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+if [ x$PDFLATEX != x ] ; then
 ## Make sure that our latex is good- it has to have the most
 ## recent version of hyperref.
 echo "$as_me:$LINENO: checking that latex is good" >&5
@@ -22916,7 +23024,8 @@ rm -f latex-test.*
 fi
 
 
-if test x$PDFLATEX != x; then
+
+if test x$PDFLATEX != x -a x$BIBTEX != x; then
   LATEXOK_TRUE=
   LATEXOK_FALSE='#'
 else
@@ -22926,9 +23035,63 @@ fi
 
 
 
+if test x$SKRIBE != x; then
+  SKRIBEOK_TRUE=
+  SKRIBEOK_FALSE='#'
+else
+  SKRIBEOK_TRUE='#'
+  SKRIBEOK_FALSE=
+fi
+
+
+
+if test x$TRIP != x; then
+  RSTOK_TRUE=
+  RSTOK_FALSE='#'
+else
+  RSTOK_TRUE='#'
+  RSTOK_FALSE=
+fi
+
+
+
+if test x$W2L != x; then
+  W2LOK_TRUE=
+  W2LOK_FALSE='#'
+else
+  W2LOK_TRUE='#'
+  W2LOK_FALSE=
+fi
+
+
+
+
+
+
+
+
+
+
+if [ x$SKRIBE = x ]; then
+  echo "! The skribe program was not found.  Documentation will not be built."
+  echo "! To build the documentation, make sure that skribe is installed and in your path."
+  echo "! You can find skribe here:  http://www-sop.inria.fr/mimosa/fp/Skribe/"
+  DOCDIR=
+fi
+
+if [ x$PDFLATEX = x -o x$BIBTEX = x ] ; then
+  echo "! PDF documentation will not be build because pdflatex could not be found."
+fi
+
+if [ x$W2L = x ] ; then
+  echo "! OpenOffice documentation will not be converted to Latex/PDF because the"
+  echo "! OpenOffice Writer -> Latex converter, writer2latex, could not be found."
+  echo "! Make sure that the w2l tool is in your path, or download and install the"
+  echo "! tool from http://www.hj-gym.dk/~hj/writer2latex/"
+fi
 
 ## Do final substitions and generation.
-CXXFLAGS="-g -Wall $CPPSETUP"
+CXXFLAGS="$CXXFLAGS -g -Wall $CPPSETUP"
 
 ## Add on macro directory to ACLOCAL_FLAGS.
 ACLOCAL_FLAGS="${ACLOCAL_FLAGS} -I ./macros"
@@ -22967,7 +23130,7 @@ fi
 
 
 # Generate configuration files.
-                                                                                                                                                                                    ac_config_files="$ac_config_files Makefile macros/Makefile scripts/Makefile qt/Makefile qt/md/Makefile src/Makefile opencxx/Makefile parser/Makefile doc/Makefile tests/Makefile tests/parsing/Makefile tests/basic/Makefile tests/sw/Makefile tests/eav/Makefile tests/ecu/Makefile tests/lemon/Makefile tests/cc/Makefile tests/cc/tests/Makefile"
+                                                                                                                                                                                              ac_config_files="$ac_config_files Makefile macros/Makefile scripts/Makefile qt/Makefile qt/md/Makefile src/Makefile opencxx/Makefile parser/Makefile doc/Makefile doc/papers/Makefile tests/Makefile tests/parsing/Makefile tests/basic/Makefile tests/sw/Makefile tests/eav/Makefile tests/ecu/Makefile tests/lemon/Makefile tests/cc/Makefile tests/cc/tests/Makefile"
 
 
                               ac_config_files="$ac_config_files scripts/plasma scripts/plasma-config tests/cc/compile_check.pm"
@@ -23148,6 +23311,27 @@ if test -z "${LATEXOK_TRUE}" && test -z "${LATEXOK_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"LATEXOK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"LATEXOK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${SKRIBEOK_TRUE}" && test -z "${SKRIBEOK_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SKRIBEOK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SKRIBEOK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${RSTOK_TRUE}" && test -z "${RSTOK_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"RSTOK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"RSTOK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${W2LOK_TRUE}" && test -z "${W2LOK_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"W2LOK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"W2LOK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -23606,6 +23790,7 @@ do
   "opencxx/Makefile" ) CONFIG_FILES="$CONFIG_FILES opencxx/Makefile" ;;
   "parser/Makefile" ) CONFIG_FILES="$CONFIG_FILES parser/Makefile" ;;
   "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
+  "doc/papers/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/papers/Makefile" ;;
   "tests/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests/Makefile" ;;
   "tests/parsing/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests/parsing/Makefile" ;;
   "tests/basic/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests/basic/Makefile" ;;
@@ -23792,9 +23977,18 @@ s,@LIBADD_DL@,$LIBADD_DL,;t t
 s,@LIBLTDL@,$LIBLTDL,;t t
 s,@INCLTDL@,$INCLTDL,;t t
 s,@SKRIBE@,$SKRIBE,;t t
+s,@BIBTEX@,$BIBTEX,;t t
 s,@PDFLATEX@,$PDFLATEX,;t t
+s,@TRIP@,$TRIP,;t t
+s,@W2L@,$W2L,;t t
 s,@LATEXOK_TRUE@,$LATEXOK_TRUE,;t t
 s,@LATEXOK_FALSE@,$LATEXOK_FALSE,;t t
+s,@SKRIBEOK_TRUE@,$SKRIBEOK_TRUE,;t t
+s,@SKRIBEOK_FALSE@,$SKRIBEOK_FALSE,;t t
+s,@RSTOK_TRUE@,$RSTOK_TRUE,;t t
+s,@RSTOK_FALSE@,$RSTOK_FALSE,;t t
+s,@W2LOK_TRUE@,$W2LOK_TRUE,;t t
+s,@W2LOK_FALSE@,$W2LOK_FALSE,;t t
 s,@PROFILE@,$PROFILE,;t t
 s,@ACLOCAL_FLAGS@,$ACLOCAL_FLAGS,;t t
 s,@WEBHOME@,$WEBHOME,;t t
