Moved website to Compass.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all gc libltdl"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP EGREP CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT RFLAG EFENCE GCC_VERSION GCC_MAJOR GCC_MINOR PERLPROG CXXPROG host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL INSTALL_LTDL_TRUE INSTALL_LTDL_FALSE CONVENIENCE_LTDL_TRUE CONVENIENCE_LTDL_FALSE LIBADD_DL LIBLTDL INCLTDL SKRIBE BIBTEX PDFLATEX TRIP W2L LATEXOK_TRUE LATEXOK_FALSE SKRIBEOK_TRUE SKRIBEOK_FALSE RSTOK_TRUE RSTOK_FALSE W2LOK_TRUE W2LOK_FALSE PROFILE ACLOCAL_FLAGS WEBHOME WEBURL DOCDIR CompileOk_TRUE CompileOk_FALSE COMPILE_OK CONFOPTS subdirs LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP EGREP CCAS CCASFLAGS LEX LEXLIB LEX_OUTPUT_ROOT RFLAG EFENCE GCC_VERSION GCC_MAJOR GCC_MINOR PERLPROG WEBURL DISTURL InfoHome CompassPlasmaDir CompassDistDir CompassParam1 CompassExists CXXPROG host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL INSTALL_LTDL_TRUE INSTALL_LTDL_FALSE CONVENIENCE_LTDL_TRUE CONVENIENCE_LTDL_FALSE LIBADD_DL LIBLTDL INCLTDL SKRIBE BIBTEX PDFLATEX TRIP W2L LATEXOK_TRUE LATEXOK_FALSE SKRIBEOK_TRUE SKRIBEOK_FALSE RSTOK_TRUE RSTOK_FALSE W2LOK_TRUE W2LOK_FALSE PROFILE ACLOCAL_FLAGS DOCDIR CompileOk_TRUE CompileOk_FALSE COMPILE_OK CONFOPTS subdirs LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1054,11 +1054,12 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-web              specify a web destination directory. The default is
-                          /proj/ppctools/GSTM/www/plasma.
   --with-weburl           specify a the URL to web documentation. The default
-                          is
-                          http://www.somerset.sps.mot.com/projects/tools/plasma.
+                          is $ac_weburl_default.
+  --with-disturl          specify a the URL to the distribution. The default
+                          is $ac_disturl_default.
+  --with-infohome         specify a web destination directory for the info.xml
+                          file. The default is $ac_infohome_default.
   --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
   --with-pic              try to use only PIC/non-PIC objects [default=use
                           both]
@@ -4542,21 +4543,8 @@ echo "$as_me: error: \"Could not find perl.  Check your path to make sure that i
 fi
 
 ## Check for web directory (documentation destination).
-echo "$as_me:$LINENO: checking for web destination directory" >&5
-echo $ECHO_N "checking for web destination directory... $ECHO_C" >&6
-ac_web_default=/proj/ppctools/GSTM/www/plasma
-ac_weburl_default=http://www.somerset.sps.mot.com/projects/tools/plasma
-WEBHOME=
 WEBURL=
-DOCDIR=doc
-
-# Check whether --with-web or --without-web was given.
-if test "${with_web+set}" = set; then
-  withval="$with_web"
-  WEBHOME=$withval
-else
-  WEBHOME=$ac_web_default
-fi;
+ac_weburl_default=http://compass.freescale.net/go/PlasmaSite
 
 # Check whether --with-weburl or --without-weburl was given.
 if test "${with_weburl+set}" = set; then
@@ -4566,14 +4554,60 @@ else
   WEBURL=$ac_weburl_default
 fi;
 
-if [ -d $WEBHOME ]; then
-  echo "$as_me:$LINENO: result: $WEBHOME" >&5
-echo "${ECHO_T}$WEBHOME" >&6
+DISTURL=
+ac_disturl_default=http://compass.freescale.net/go/PlasmaDist
+
+# Check whether --with-disturl or --without-disturl was given.
+if test "${with_disturl+set}" = set; then
+  withval="$with_disturl"
+  DISTURL=$withval
 else
-  echo "$as_me:$LINENO: result: Directory $WEBHOME not found.  Documentation will not be installed." >&5
-echo "${ECHO_T}Directory $WEBHOME not found.  Documentation will not be installed." >&6
-  DOCDIR=
+  DISTURL=$ac_disturl_default
+fi;
+
+
+echo "$as_me:$LINENO: checking for info destination directory" >&5
+echo $ECHO_N "checking for info destination directory... $ECHO_C" >&6
+ac_infohome_default=/proj/ppctools/www/a-z/plasma
+InfoHome=
+DOCDIR=doc
+
+# Check whether --with-infohome or --without-infohome was given.
+if test "${with_infohome+set}" = set; then
+  withval="$with_infohome"
+  InfoHome=$withval
+else
+  InfoHome=$ac_infohome_default
+fi;
+if [ -d $InfoHome ]; then
+  echo "$as_me:$LINENO: result: $InfoHome" >&5
+echo "${ECHO_T}$InfoHome" >&6
+else
+  echo "$as_me:$LINENO: result: Directory $InfoHome not found.  Documentation will not be installed." >&5
+echo "${ECHO_T}Directory $InfoHome not found.  Documentation will not be installed." >&6
 fi
+
+
+## Check to see if compass exists.  If not, then we don't install documentation.
+echo "$as_me:$LINENO: checking to see if Compass exists" >&5
+echo $ECHO_N "checking to see if Compass exists... $ECHO_C" >&6
+CompassPlasmaDir=162987954
+CompassDistDir=162979417
+CompassParam1=QXJkMXZhcmsh
+CompassExists=1
+`ping -c 1 compass.freescale.net > /dev/null` || CompassExists=
+if [ !$CompassExists ] ; then
+	echo "$as_me:$LINENO: result: yes.  Documentation will be installed to Compass." >&5
+echo "${ECHO_T}yes.  Documentation will be installed to Compass." >&6
+else
+	echo "$as_me:$LINENO: result: no.  Documentation will not be installed." >&5
+echo "${ECHO_T}no.  Documentation will not be installed." >&6
+fi
+
+
+
+
+
 
 ## Get the full compiler path.
 # Extract the first word of "$CXX", so it can be a program name with args.
@@ -5278,7 +5312,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5281 "configure"' > conftest.$ac_ext
+  echo '#line 5315 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5991,7 +6025,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5994:" \
+echo "$as_me:6028:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7052,11 +7086,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7055: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7089: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7059: \$? = $ac_status" >&5
+   echo "$as_me:7093: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -7295,11 +7329,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7298: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7332: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7302: \$? = $ac_status" >&5
+   echo "$as_me:7336: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -7355,11 +7389,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7358: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7392: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7362: \$? = $ac_status" >&5
+   echo "$as_me:7396: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9540,7 +9574,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9543 "configure"
+#line 9577 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9638,7 +9672,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9641 "configure"
+#line 9675 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11835,11 +11869,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11838: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11872: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11842: \$? = $ac_status" >&5
+   echo "$as_me:11876: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11895,11 +11929,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11898: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11932: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11902: \$? = $ac_status" >&5
+   echo "$as_me:11936: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13256,7 +13290,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13259 "configure"
+#line 13293 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13354,7 +13388,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13357 "configure"
+#line 13391 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14191,11 +14225,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14194: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14228: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14198: \$? = $ac_status" >&5
+   echo "$as_me:14232: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -14251,11 +14285,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14254: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14288: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14258: \$? = $ac_status" >&5
+   echo "$as_me:14292: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16290,11 +16324,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16293: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16327: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16297: \$? = $ac_status" >&5
+   echo "$as_me:16331: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16533,11 +16567,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16536: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16570: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16540: \$? = $ac_status" >&5
+   echo "$as_me:16574: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16593,11 +16627,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16596: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16630: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16600: \$? = $ac_status" >&5
+   echo "$as_me:16634: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18778,7 +18812,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18781 "configure"
+#line 18815 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18876,7 +18910,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18879 "configure"
+#line 18913 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21215,7 +21249,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 21218 "configure"
+#line 21252 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -23104,8 +23138,6 @@ ACLOCAL_FLAGS="${ACLOCAL_FLAGS} -I ./macros"
 
 
 
-
-
 # If compiling on x86, we can compile test programs generated
 # by the sample compiler in the regression suite.
 if [ $build_cpu = i686 ]; then
@@ -23956,6 +23988,13 @@ s,@GCC_VERSION@,$GCC_VERSION,;t t
 s,@GCC_MAJOR@,$GCC_MAJOR,;t t
 s,@GCC_MINOR@,$GCC_MINOR,;t t
 s,@PERLPROG@,$PERLPROG,;t t
+s,@WEBURL@,$WEBURL,;t t
+s,@DISTURL@,$DISTURL,;t t
+s,@InfoHome@,$InfoHome,;t t
+s,@CompassPlasmaDir@,$CompassPlasmaDir,;t t
+s,@CompassDistDir@,$CompassDistDir,;t t
+s,@CompassParam1@,$CompassParam1,;t t
+s,@CompassExists@,$CompassExists,;t t
 s,@CXXPROG@,$CXXPROG,;t t
 s,@host@,$host,;t t
 s,@host_cpu@,$host_cpu,;t t
@@ -23994,8 +24033,6 @@ s,@W2LOK_TRUE@,$W2LOK_TRUE,;t t
 s,@W2LOK_FALSE@,$W2LOK_FALSE,;t t
 s,@PROFILE@,$PROFILE,;t t
 s,@ACLOCAL_FLAGS@,$ACLOCAL_FLAGS,;t t
-s,@WEBHOME@,$WEBHOME,;t t
-s,@WEBURL@,$WEBURL,;t t
 s,@DOCDIR@,$DOCDIR,;t t
 s,@CompileOk_TRUE@,$CompileOk_TRUE,;t t
 s,@CompileOk_FALSE@,$CompileOk_FALSE,;t t
